#spring.config.activate.on-profile=local

secure-key-manager:
  password: ${KEY_MANAGER_PASSWORD}
  url: https://api-keymanager.nhncloudservice.com
  path: /keymanager/v1.0/appkey/{appkey}/secrets/{keyid}
  appKey: ${KEY_MANAGER_APP_KEY}

nhn:
  cloud:
    object-storage:
      access-key: ${STORAGE_ACCESS_KEY}
      endpoint: https://kr1-api-object-storage.nhncloudservice.com
      version: v1
      auth: AUTH_04475dda7b414b0f91191adf7d62aa0ds
      secret-key: ${STORAGE_SECRET_KEY}
      bucket-name: inkbridge-refactoring