### 주소 생성
POST http://localhost:8080/api/my/addresses
Authorization-Id: 1
Content-Type: application/json

{
  "receiverName": "최재훈5",
  "receiverPhone": "010-1234-5678",
  "roadName": "서울특별시 강남구 테헤란로 123",
  "addressDetail": "101동 202호",
  "zipCode": "06234",
  "isDefault": false
}

### 주소 수정
PUT http://localhost:8080/api/my/addresses
Authorization-Id: 1
Content-Type: application/json

{
  "id": 25,
  "receiverName": "최재훈1",
  "receiverPhone": "010-1234-5678",
  "roadName": "서울특별시 강남구 테헤란로 124",
  "addressDetail": "101동 202호",
  "zipCode": "06234",
  "isDefault": false
}

### 주소 삭제
DELETE http://localhost:8080/api/my/addresses/22
Authorization-Id: 1

### 주소록 조회
GET http://localhost:8080/api/my/addresses
Authorization-Id: 1

### 주소 조회
GET http://localhost:8080/api/my/addresses/22
Authorization-Id: 1


### 멤버 등급 목록 조회
GET http://localhost:8080/api/my/grades
Authorization-Id: 1
